/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PhotoViewResponse } from '../../models/photo-view-response';
import { ReorderPhotosBody } from '../../models/reorder-photos-body';

export interface MyItemsControllerReorderPhotos$Params {
  itemId: string;
      body: ReorderPhotosBody
}

export function myItemsControllerReorderPhotos(http: HttpClient, rootUrl: string, params: MyItemsControllerReorderPhotos$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PhotoViewResponse>>> {
  const rb = new RequestBuilder(rootUrl, myItemsControllerReorderPhotos.PATH, 'put');
  if (params) {
    rb.path('itemId', params.itemId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<PhotoViewResponse>>;
    })
  );
}

myItemsControllerReorderPhotos.PATH = '/api/me/items/{itemId}/photos/order';
