/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OwnItemResponse } from '../../models/own-item-response';

export interface MyItemsControllerGet$Params {
  itemId: string;
}

export function myItemsControllerGet(http: HttpClient, rootUrl: string, params: MyItemsControllerGet$Params, context?: HttpContext): Observable<StrictHttpResponse<OwnItemResponse>> {
  const rb = new RequestBuilder(rootUrl, myItemsControllerGet.PATH, 'get');
  if (params) {
    rb.path('itemId', params.itemId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OwnItemResponse>;
    })
  );
}

myItemsControllerGet.PATH = '/api/me/items/{itemId}';
