/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreatePhotoUploadBody } from '../../models/create-photo-upload-body';
import { PhotoUploadResponse } from '../../models/photo-upload-response';

export interface MyItemsControllerCreatePhotoUpload$Params {
  itemId: string;
      body: CreatePhotoUploadBody
}

export function myItemsControllerCreatePhotoUpload(http: HttpClient, rootUrl: string, params: MyItemsControllerCreatePhotoUpload$Params, context?: HttpContext): Observable<StrictHttpResponse<PhotoUploadResponse>> {
  const rb = new RequestBuilder(rootUrl, myItemsControllerCreatePhotoUpload.PATH, 'post');
  if (params) {
    rb.path('itemId', params.itemId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PhotoUploadResponse>;
    })
  );
}

myItemsControllerCreatePhotoUpload.PATH = '/api/me/items/{itemId}/photos';
