/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OwnItemResponse } from '../../models/own-item-response';
import { UpdateItemBody } from '../../models/update-item-body';

export interface MyItemsControllerUpdate$Params {
  itemId: string;
      body: UpdateItemBody
}

export function myItemsControllerUpdate(http: HttpClient, rootUrl: string, params: MyItemsControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<OwnItemResponse>> {
  const rb = new RequestBuilder(rootUrl, myItemsControllerUpdate.PATH, 'patch');
  if (params) {
    rb.path('itemId', params.itemId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OwnItemResponse>;
    })
  );
}

myItemsControllerUpdate.PATH = '/api/me/items/{itemId}';
