/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateItemBody } from '../../models/create-item-body';
import { OwnItemResponse } from '../../models/own-item-response';

export interface MyItemsControllerCreate$Params {
      body: CreateItemBody
}

export function myItemsControllerCreate(http: HttpClient, rootUrl: string, params: MyItemsControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<OwnItemResponse>> {
  const rb = new RequestBuilder(rootUrl, myItemsControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OwnItemResponse>;
    })
  );
}

myItemsControllerCreate.PATH = '/api/me/items';
