/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DataExportResponse } from '../../models/data-export-response';

export interface MeControllerExport$Params {
}

export function meControllerExport(http: HttpClient, rootUrl: string, params?: MeControllerExport$Params, context?: HttpContext): Observable<StrictHttpResponse<DataExportResponse>> {
  const rb = new RequestBuilder(rootUrl, meControllerExport.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DataExportResponse>;
    })
  );
}

meControllerExport.PATH = '/api/me/export';
