/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ApiErrorResponse {

  /**
   * Stable machine-readable code, e.g. VALIDATION_FAILED, INVALID_CREDENTIALS, EMAIL_TAKEN, RATE_LIMITED
   */
  code: string;
  message: string;
  statusCode: number;
}
