/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserProfileResponse } from '../models/user-profile-response';
export interface AuthResponse {

  /**
   * Bearer token for `Authorization` (15 min)
   */
  accessToken: string;
  accessTokenExpiresAt: string;
  user: UserProfileResponse;
}
