/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LenderProfileResponse } from '../models/lender-profile-response';
import { OwnItemResponse } from '../models/own-item-response';
export interface CatalogDataExportResponse {
  exportedAt: string;
  items: Array<OwnItemResponse>;
  lenderProfile: (LenderProfileResponse & {
}) | null;
}
