/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ItemCategory } from '../models/item-category';
import { ItemPricingBody } from '../models/item-pricing-body';
export interface CreateItemBody {
  category: ItemCategory;
  depositCents: number;
  description?: string;

  /**
   * A new random UUID chosen by the client once per item: sending the same create again returns the same item.
   */
  itemId: string;
  pricing: ItemPricingBody;
  title: string;
}
