/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PhotoContentType } from '../models/photo-content-type';
export interface CreatePhotoUploadBody {
  contentType: PhotoContentType;
  sizeBytes: number;
}
