/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { IdentityDataExportResponse } from '../models/identity-data-export-response';
export interface DataExportResponse {
  identity: IdentityDataExportResponse;
}
