/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CatalogDataExportResponse } from '../models/catalog-data-export-response';
import { IdentityDataExportResponse } from '../models/identity-data-export-response';
export interface DataExportResponse {
  catalog: CatalogDataExportResponse;
  identity: IdentityDataExportResponse;
}
