/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DeleteAccountBody {

  /**
   * Required when the account has a password (`UserProfile.hasPassword`). Otherwise the session must be less than 5 minutes old.
   */
  password?: string;
}
