/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DistanceBand } from './distance-band';

/**
 * Each possible value of `DistanceBand`
 */
export const DISTANCE_BAND: DistanceBand[] = [
  'UNDER_1_KM',
  '1_2_KM',
  '2_5_KM',
  '5_10_KM',
  'OVER_10_KM'
];