/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OAuthProvider } from '../models/o-auth-provider';
export interface ExportedOAuthIdentity {
  linkedAt: string;
  provider: OAuthProvider;
}
