/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Locale } from '../models/locale';
export interface ExportedUser {
  createdAt: string;
  displayName: string;
  email: string;
  emailVerifiedAt: string | null;
  id: string;
  locale: Locale;
  updatedAt: string;
}
