/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ExportedOAuthIdentity } from '../models/exported-o-auth-identity';
import { ExportedSession } from '../models/exported-session';
import { ExportedUser } from '../models/exported-user';
export interface IdentityDataExportResponse {
  exportedAt: string;
  oauthIdentities: Array<ExportedOAuthIdentity>;
  sessions: Array<ExportedSession>;
  user: ExportedUser;
}
