/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ItemCategory } from './item-category';

/**
 * Each possible value of `ItemCategory`
 */
export const ITEM_CATEGORY: ItemCategory[] = [
  'tools',
  'diy-ladders',
  'garden',
  'cleaning',
  'kitchen',
  'electronics',
  'photo-video',
  'music',
  'sports',
  'camping',
  'travel',
  'kids',
  'party',
  'vehicles',
  'other'
];