/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DistanceBand } from '../models/distance-band';
export interface ItemSuggestionResponse {
  distanceBand: DistanceBand;
  id: string;
  thumbnailUrl: string | null;
  title: string;
}
