/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type ItemCategory = 'tools' | 'diy-ladders' | 'garden' | 'cleaning' | 'kitchen' | 'electronics' | 'photo-video' | 'music' | 'sports' | 'camping' | 'travel' | 'kids' | 'party' | 'vehicles' | 'other';

