/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ItemPricingBody {
  dailyCents?: number;

  /**
   * Free items offer no rates
   */
  free: boolean;
  hourlyCents?: number;
  monthlyCents?: number;
  weeklyCents?: number;
}
