/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ItemStatus } from './item-status';

/**
 * Each possible value of `ItemStatus`
 */
export const ITEM_STATUS: ItemStatus[] = [
  'DRAFT',
  'ACTIVE',
  'PAUSED',
  'DELETED'
];