/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OAuthProvider } from './o-auth-provider';

/**
 * Each possible value of `OAuthProvider`
 */
export const O_AUTH_PROVIDER: OAuthProvider[] = [
  'google'
];