/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GeoPointResponse } from '../models/geo-point-response';
import { ItemCategory } from '../models/item-category';
import { ItemPricingBody } from '../models/item-pricing-body';
import { ItemStatus } from '../models/item-status';
import { PhotoViewResponse } from '../models/photo-view-response';
export interface OwnItemResponse {

  /**
   * What everyone else sees (ADR-0007)
   */
  approximateLocation: (GeoPointResponse & {
}) | null;
  category: ItemCategory;
  createdAt: string;
  depositCents: number;
  description: string;
  id: string;

  /**
   * The exact pin; only ever sent to the owner
   */
  location: (GeoPointResponse & {
}) | null;
  photos: Array<PhotoViewResponse>;
  pricing: ItemPricingBody;
  publishedAt: string | null;
  status: ItemStatus;
  title: string;
  updatedAt: string;
}
