/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PhotoUrlsResponse {

  /**
   * 1600 px wide WebP (or the original width)
   */
  large: string;

  /**
   * 800 px wide WebP (or the original width)
   */
  medium: string;

  /**
   * 320 px wide WebP
   */
  small: string;
}
