/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PhotoStatus } from '../models/photo-status';
import { PhotoUrlsResponse } from '../models/photo-urls-response';
export interface PhotoViewResponse {
  id: string;

  /**
   * 0 is the cover
   */
  position: number;
  status: PhotoStatus;

  /**
   * Set once READY
   */
  urls: (PhotoUrlsResponse & {
}) | null;
}
