/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PhotoContentType } from './photo-content-type';

/**
 * Each possible value of `PhotoContentType`
 */
export const PHOTO_CONTENT_TYPE: PhotoContentType[] = [
  'image/jpeg',
  'image/png',
  'image/webp',
  'image/avif',
  'image/gif',
  'image/tiff'
];