/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PhotoStatus } from './photo-status';

/**
 * Each possible value of `PhotoStatus`
 */
export const PHOTO_STATUS: PhotoStatus[] = [
  'PENDING',
  'READY',
  'FAILED'
];