/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PhotoUploadResponse {
  expiresAt: string;
  photoId: string;

  /**
   * Headers the PUT must send exactly
   */
  uploadHeaders: {
[key: string]: string;
};

  /**
   * PUT the file here, before expiresAt
   */
  uploadUrl: string;
}
