/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PriceUnit } from './price-unit';

/**
 * Each possible value of `PriceUnit`
 */
export const PRICE_UNIT: PriceUnit[] = [
  'HOUR',
  'DAY',
  'WEEK',
  'MONTH'
];