/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PhotoUrlsResponse } from '../models/photo-urls-response';
export interface PublicPhotoResponse {
  id: string;
  urls: PhotoUrlsResponse;
}
