/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GeoPointResponse } from '../models/geo-point-response';
import { ItemCategory } from '../models/item-category';
import { ItemPricingBody } from '../models/item-pricing-body';
import { LenderSummaryResponse } from '../models/lender-summary-response';
import { PublicPhotoResponse } from '../models/public-photo-response';
export interface PublicItemDetailResponse {
  approximateLocation: GeoPointResponse;
  category: ItemCategory;
  depositCents: number;
  description: string;
  id: string;
  lender: LenderSummaryResponse;
  photos: Array<PublicPhotoResponse>;
  pricing: ItemPricingBody;
  publishedAt: string;
  title: string;
}
