/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DistanceBand } from '../models/distance-band';
import { GeoPointResponse } from '../models/geo-point-response';
import { ItemCategory } from '../models/item-category';
import { ItemPricingBody } from '../models/item-pricing-body';
import { LenderSummaryResponse } from '../models/lender-summary-response';
import { PhotoUrlsResponse } from '../models/photo-urls-response';
export interface PublicItemSummaryResponse {
  approximateLocation: GeoPointResponse;
  category: ItemCategory;
  coverPhoto: (PhotoUrlsResponse & {
}) | null;
  depositCents: number;
  distanceBand: DistanceBand;
  id: string;
  lender: LenderSummaryResponse;
  pricing: ItemPricingBody;
  title: string;
}
