/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Locale } from '../models/locale';
export interface RegisterBody {
  displayName: string;
  email: string;
  locale?: Locale;

  /**
   * At least one letter and one digit
   */
  password: string;
}
