/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ReorderPhotosBody {

  /**
   * Every photo of the item, in the new order
   */
  photoIds: Array<string>;
}
