/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SearchRadiusKm } from './search-radius-km';

/**
 * Each possible value of `SearchRadiusKm`
 */
export const SEARCH_RADIUS_KM: SearchRadiusKm[] = [
  1,
  2,
  5,
  10,
  25,
  50
];