/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GeoPointBody } from '../models/geo-point-body';
import { ItemCategory } from '../models/item-category';
import { PriceUnit } from '../models/price-unit';
import { SearchRadiusKm } from '../models/search-radius-km';
export interface SearchItemsBody {
  category?: ItemCategory;

  /**
   * From the previous page's nextCursor
   */
  cursor?: string;
  freeOnly?: boolean;
  limit?: number;

  /**
   * With priceUnit: items offering that unit at or below this rate, and free items (ADR-0012)
   */
  maxPriceCents?: number;

  /**
   * Used for this search only; never stored or logged.
   */
  near: GeoPointBody;
  priceUnit?: PriceUnit;
  q?: string;
  radiusKm: SearchRadiusKm;
}
