/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PublicItemSummaryResponse } from '../models/public-item-summary-response';
export interface SearchItemsResponse {
  items: Array<PublicItemSummaryResponse>;

  /**
   * Null on the last page
   */
  nextCursor: string | null;
}
