/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GeoPointBody } from '../models/geo-point-body';
export interface SetItemLocationBody {

  /**
   * The exact point (a dropped pin). Only the owner ever sees it; everyone else sees a point 150-300 m away (ADR-0007).
   */
  location: GeoPointBody;
}
