/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PublicItemSummaryResponse } from '../models/public-item-summary-response';
export interface SimilarItemsResponse {

  /**
   * distanceBand is measured from the item
   */
  items: Array<PublicItemSummaryResponse>;
}
