/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GeoPointBody } from '../models/geo-point-body';
import { SearchRadiusKm } from '../models/search-radius-km';
export interface SuggestItemsBody {

  /**
   * Used for this request only; never stored or logged.
   */
  near: GeoPointBody;

  /**
   * What has been typed so far
   */
  q: string;
  radiusKm: SearchRadiusKm;
}
