/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ItemSuggestionResponse } from '../models/item-suggestion-response';
export interface SuggestItemsResponse {
  suggestions: Array<ItemSuggestionResponse>;
}
