/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ItemCategory } from '../models/item-category';
import { ItemPricingBody } from '../models/item-pricing-body';
export interface UpdateItemBody {
  category?: ItemCategory;
  depositCents?: number;
  description?: string;
  pricing?: ItemPricingBody;
  title?: string;
}
