/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Locale } from '../models/locale';
import { OAuthProvider } from '../models/o-auth-provider';
export interface UserProfileResponse {
  createdAt: string;
  displayName: string;
  email: string;
  emailVerified: boolean;
  hasPassword: boolean;
  id: string;
  locale: Locale;
  providers: Array<OAuthProvider>;
}
