/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SuggestItemsBody } from '../../models/suggest-items-body';
import { SuggestItemsResponse } from '../../models/suggest-items-response';

export interface PublicItemsControllerSuggest$Params {
      body: SuggestItemsBody
}

export function publicItemsControllerSuggest(http: HttpClient, rootUrl: string, params: PublicItemsControllerSuggest$Params, context?: HttpContext): Observable<StrictHttpResponse<SuggestItemsResponse>> {
  const rb = new RequestBuilder(rootUrl, publicItemsControllerSuggest.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuggestItemsResponse>;
    })
  );
}

publicItemsControllerSuggest.PATH = '/api/items/suggest';
