/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SearchItemsBody } from '../../models/search-items-body';
import { SearchItemsResponse } from '../../models/search-items-response';

export interface PublicItemsControllerSearch$Params {
      body: SearchItemsBody
}

export function publicItemsControllerSearch(http: HttpClient, rootUrl: string, params: PublicItemsControllerSearch$Params, context?: HttpContext): Observable<StrictHttpResponse<SearchItemsResponse>> {
  const rb = new RequestBuilder(rootUrl, publicItemsControllerSearch.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SearchItemsResponse>;
    })
  );
}

publicItemsControllerSearch.PATH = '/api/items/search';
