/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PublicItemDetailResponse } from '../../models/public-item-detail-response';

export interface PublicItemsControllerGet$Params {
  itemId: string;
}

export function publicItemsControllerGet(http: HttpClient, rootUrl: string, params: PublicItemsControllerGet$Params, context?: HttpContext): Observable<StrictHttpResponse<PublicItemDetailResponse>> {
  const rb = new RequestBuilder(rootUrl, publicItemsControllerGet.PATH, 'get');
  if (params) {
    rb.path('itemId', params.itemId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PublicItemDetailResponse>;
    })
  );
}

publicItemsControllerGet.PATH = '/api/items/{itemId}';
